sudo: required
dist: xenial
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - pkg-config
    - libsdl1.2-dev
    - libsdl-ttf2.0-dev
    - valgrind
env:
  matrix:
   - CFLAGS="--coverage"
   - CFLAGS="-O3"
   - TESTRUN_WRAPPER='valgrind -q --error-exitcode=126 --track-origins=yes --leak-check=full' CFLAGS="-O1 -g3"
   - CFLAGS="-g3 -fsanitize=undefined -fsanitize=address -fsanitize=leak"
script:
 - make clean && make -j$(nproc) test

matrix:
  include:
    # test without sdl installed
    - os: linux
      script:
      - make CONFIG_fft_eval_sdl=n CONFIG_fft_eval_json=y clean && make CONFIG_fft_eval_sdl=n CONFIG_fft_eval_json=y test
